[mod]tuning parameter of keepalived; modify notify-scripts

diff --git a/playbook/roles/keepalived/templates/keepalived_to_be_master.sh.j2 b/playbook/roles/keepalived/templates/keepalived_to_be_master.sh.j2
--- a/playbook/roles/keepalived/templates/keepalived_to_be_master.sh.j2
+++ b/playbook/roles/keepalived/templates/keepalived_to_be_master.sh.j2
@@ -7,18 +7,35 @@ for TRIES in `seq 1 3`
 do
   ssh root@{{ keepalived_neighbor }} service keepalived status
   NEIGHBOR_IS_ALIVE=$?
-  ping -c 1 -w 1 {{ keepalived.gateway_ip }}
-  NETWORK_IS_ALIVE=$?
 
-  if [ $NEIGHBOR_IS_ALIVE = 0 ] || [ $NETWORK_IS_ALIVE = 0 ]; then
+  if [ $NEIGHBOR_IS_ALIVE = 0 ]; then
+    echo "Neighbor's keepalived Health Check is OK" | logger -i -t keepalived-vrrp
     exit 0
   fi
-  echo "Gateway and neighbor check failed ${TRIES} times" | logger -i -t keepalived-vrrp
+
+  echo "Neighbor's keepalived health check failed ${TRIES} times" | logger -i -t keepalived-vrrp
   sleep $INTERVAL
 done
 
-echo "Network down detected. There is a possiblility of split brain syndrome, therefore shutdown mysqld and keepalived." | logger -i -t keepalived-vrrp
-service mysqld stop
-service keepalived stop
-echo "mysqld and keepalived shutdown done." | logger -i -t keepalived-vrrp
+ping -c 1 -w 1 {{ keepalived.gateway_ip }}
+NETWORK_IS_ALIVE=$?
+
+if [ $NETWORK_IS_ALIVE = 0 ]; then
+  # in case as below
+  #   1. master's keepalived process down occur.
+  #      therefore shutdown neighbor's mysqld to switch replica.
+  echo "Neighbor's keepalived is down, therefore shutdown neighbor's mysqld." | logger -i -t keepalived-vrrp
+  ssh root@{{ keepalived_neighbor }} service mysqld stop
+else
+  # in case as below
+  #   1. network trouble between master and slave is happen,
+  #      therefore there is a possibility of split brain syndrome
+  #   2. master's nic trouble is happen.
+  #   3. master's chassis (pr VM) trouble is happen.
+  echo "Network down detected. There is a possiblility of split brain syndrome, therefore shutdown mysqld and keepalived." | logger -i -t keepalived-vrrp
+  ssh root@{{ keepalived_neighbor }} service mysqld stop
+  ssh root@{{ keepalived_neighbor }} service keepalived stop
+  echo "mysqld and keepalived shutdown done." | logger -i -t keepalived-vrrp
+fi
+
 exit 1
